export const LOGIN_REQUEST_START = 'LOGIN_REQUEST_START'
export const LOGIN_REQUEST_END = 'LOGIN_REQUEST_END'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
